# change this to the name of the repository and have it in all lower caps
baseurl: "/siliconvalley"

# change this to the name of your city
city: Silicon Valley
# color names taken from http://materializecss.com/color.html
# append '-text' to color2 names and prepend accent/darken with 'text-'
city_color:  light-green lighten-1
city_color2: darken-4-text
logo_color: black # either black or white